### ISSUE TITLE
Doubline segments mode doesn't work inside a request from the Alignment Editor

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/tokenizer#17]
![image](https://user-images.githubusercontent.com/12377640/97518533-16757880-19e3-11eb-9b1b-9c43abdf21fd.png)

Request URL: https://tools.alpheios.net/tokenizer/tokenize/text?lang=lat&segments=doubline
![image](https://user-images.githubusercontent.com/12377640/97518593-40c73600-19e3-11eb-902d-6fa5e03601d7.png)

![image](https://user-images.githubusercontent.com/12377640/97518606-4886da80-19e3-11eb-9342-3ba9cd733648.png)

**Comment by balmas** [comment]
this was because of a typo in the field defaults in the schema (see #20). It should have been 'doubleline' not 'doubline'.
