### ISSUE TITLE
normalize > 2 new lines in a row in plain text input

### ISSUE THREAD

**Issue by balmas** [alpheios-project/tokenizer#22]
> I tested the case when we have more than two new lines
> ![image](https://user-images.githubusercontent.com/12377640/101619611-3d51b080-3a5f-11eb-9531-b12ab0beaba9.png)
> 
> And defined `doubleline` segmentation
> It will return a single segment
> 
> ![image](https://user-images.githubusercontent.com/12377640/101619797-78ec7a80-3a5f-11eb-9001-084b93769e50.png)
> 
> Does it a tokenization service bug?
> 
> Should we save such additional new lines?
> Are such cases (to use more than one new line in a row inside a segment) the part of the requirement:
> 

we do not have a requirement to support more than one new line in a row inside a segment.

the tokenization service should probably ignore any newlines above 2 in a row. I'll make this an issue there.

_Originally posted by @balmas in https://github.com/alpheios-project/alignment-editor-new/issues/63#issuecomment-741749706_

**Comment by monzug** [comment]
Actually, in case of more than 2 lines and doubleline as segment separator, no segment is generated. see attachments of origin text and alignment

![morethan2lines](https://user-images.githubusercontent.com/41396793/102371583-53460080-3f8c-11eb-9006-e244b4ff50f9.JPG)

![alignment-morethan2lines](https://user-images.githubusercontent.com/41396793/102371703-796ba080-3f8c-11eb-8d60-eb27666f1653.JPG)

**Comment by balmas** [comment]
> 2 lines in a row should now be interpreted as 2 lines.

**Comment by monzug** [comment]
see screenshot of  above example. Fixed

![more-than-2-rows](https://user-images.githubusercontent.com/41396793/103294295-9908bd00-49bf-11eb-9be5-91a739c238cb.JPG)
