### ISSUE TITLE
empty alignment group with TEI.2 tag

### ISSUE THREAD

**Issue by monzug** [alpheios-project/tokenizer#29]
with the  <TEI.2>  xml  tag  from perseus (e.g. www.perseus.tufts.edu/hopper/xmlchunk?doc=Perseus%3Atext%3A2008.01.0594%3Achapter%3D8 ) I do not get any error in tokenization but the alignment groups is empty. if I replace the TEI.2 with the one we have in alpheios (TEI xmlns="http://www.tei-c.org/ns/1.0" xmlns:py="http://codespeak.net/lxml/objectify/pytype" py:pytype="TREE") it works.

![empty-alignment](https://user-images.githubusercontent.com/41396793/103295333-b76fb800-49c1-11eb-9caf-7f3902dcc55a.JPG)

**Comment by monzug** [comment]
to test also with two target texts (to upload file alignment-lat-lat-eng.tsv)

**Comment by irina060981** [comment]
I checked this case with TEI.2, the problem is that the following tag is not enough
`<TEI.2`
should be
`<TEI.2 xmlns="http://www.tei-c.org/ns/1.0">`

With this definition tokenization works properly.
Would send this question to Bridgit too

**Comment by monzug** [comment]
yes, that's how I changed it to successfully align

**Comment by irina060981** [comment]
I have updated tokenizer service to support TEI tags without namespace.
How it checks:

1. First it searches for dts:fragment tag (it is for DTS texts)
2. If fails - it searches for the tag with namespace xmlns = "http://www.tei-c.org/ns/1.0"   

This steps were before my update
I have added

3. If fails - it searches for <text> tag and gets text from it (and all inner nodes)

So now all these templates are rendered

```
<TEI>
<text>
this is body text
</text>
</TEI>
```

```
<TEI xmlns="http://www.tei-c.org/ns/1.0">  
<text>
this is body text
</text>
</TEI>
```

```
<TEI.2>
<text>
this is body text
</text>
</TEI.2>
```

```
<TEI.2 xmlns="http://www.tei-c.org/ns/1.0">
<text>
this is body text
</text>
</TEI.2>
```

**Comment by irina060981** [comment]
I found one edge case - 
if you try to tokenize xml with tei namespace that is not equal to "http://www.tei-c.org/ns/1.0", than it fails

I didn't find the way to make namespace less concrete , but I checked and didn't find other correct namespace for TEI.

If we want to support xml with other namespace - I should spend more time and some examples.

**Comment by irina060981** [comment]
ok, thank you, @monzug , I think that is really difficult to find all variants at once.
But I will be able to do fixes based on examples
