### ISSUE TITLE
rtl/ltr input parameter needed?

### ISSUE THREAD

**Issue by balmas** [alpheios-project/tokenizer#4]
> @balmas , also we don't pass ltr/rtl - so do we need this parameter only for alignment-editor?

It's a good question. I think the language model should handle it appropriately but it could be that we will need it. I will add an issue for myself about that.

_Originally posted by @balmas in https://github.com/alpheios-project/tokenizer/issues/3#issuecomment-694249045_

**Comment by irina060981** [comment]
this was done - this parameter is passed to tokenizer service
